# Generated by Django 4.2.9 on 2025-01-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_no", models.CharField(max_length=100)),
                ("complaint_date", models.DateField()),
                ("case_name", models.CharField(max_length=255)),
                ("case_status", models.CharField(max_length=100)),
                ("court_name", models.CharField(max_length=255)),
                ("litigation_venues", models.TextField()),
                ("related_cases", models.TextField(blank=True, null=True)),
                ("case_closed_date", models.DateField(blank=True, null=True)),
                ("cause_of_action", models.TextField()),
                ("accused_product", models.TextField()),
                (
                    "assigned_judge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_infringed_claims", models.IntegerField()),
                (
                    "third_party_funding_involved",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("type_of_infringement", models.CharField(max_length=255)),
                ("case_strength_level", models.CharField(max_length=50)),
                ("recent_action", models.TextField(blank=True, null=True)),
                (
                    "winning_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "winning_party",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("other_possible_infringer", models.TextField(blank=True, null=True)),
                ("list_of_prior_art", models.TextField(blank=True, null=True)),
                ("patent_no", models.TextField(blank=True, null=True)),
                ("patent_type", models.TextField(blank=True, null=True)),
                ("patent_title", models.TextField(blank=True, null=True)),
                ("original_assignee", models.CharField(max_length=255)),
                (
                    "current_assignee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("single_or_multiple", models.CharField(max_length=50)),
                ("standard_patent", models.CharField(max_length=20)),
                ("semiconductor_patent", models.CharField(max_length=20)),
                ("tech_center", models.CharField(max_length=255)),
                ("art_unit", models.CharField(max_length=100)),
                ("acquisition_type", models.CharField(max_length=255)),
                ("assignee_timeline", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(max_length=255)),
                ("technology_keywords", models.TextField()),
                ("tech_category", models.CharField(max_length=255)),
                ("reason_of_allowance", models.TextField()),
                ("plaintiff", models.TextField(blank=True, null=True)),
                ("plaintiff_type_and_size", models.TextField(blank=True, null=True)),
                ("plaintiff_law_firm", models.TextField(blank=True, null=True)),
                ("plaintiff_attorney_name", models.TextField(blank=True, null=True)),
                ("plaintiff_contact", models.TextField(blank=True, null=True)),
                ("plaintiff_email", models.TextField(blank=True, null=True)),
                ("defendant", models.TextField(blank=True, null=True)),
                ("defendent_type_and_size", models.TextField(blank=True, null=True)),
                ("defendant_law_firm", models.TextField(blank=True, null=True)),
                ("defendant_attorney_name", models.TextField(blank=True, null=True)),
                ("defendant_phone", models.TextField(blank=True, null=True)),
                ("defendant_email", models.TextField(blank=True, null=True)),
                ("stage", models.CharField(max_length=20)),
            ],
        ),
    ]
