# Generated by Django 4.2.9 on 2025-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="accused_product",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="acquisition_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="art_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_strength_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="cause_of_action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="complaint_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="court_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="expiry_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="issue_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="litigation_venues",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="number_of_infringed_claims",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="original_assignee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="reason_of_allowance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="semiconductor_patent",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="single_or_multiple",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="stage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="standard_patent",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="tech_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="tech_center",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="technology_keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="type_of_infringement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="winning_amount",
            field=models.TextField(blank=True, null=True),
        ),
    ]
