# Generated by Django 4.2.18 on 2025-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casedetails',
            old_name='defendent_type_and_size',
            new_name='defendent_count',
        ),
        migrations.RenameField(
            model_name='casedetails',
            old_name='plaintiff_type_and_size',
            new_name='defendent_size',
        ),
        migrations.RenameField(
            model_name='rawdata',
            old_name='defendent_type_and_size',
            new_name='defendent_count',
        ),
        migrations.RenameField(
            model_name='rawdata',
            old_name='plaintiff_type_and_size',
            new_name='defendent_size',
        ),
        migrations.AddField(
            model_name='casedetails',
            name='defendent_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='plaintiff_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='plaintiff_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='plaintiff_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='defendent_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='plaintiff_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='plaintiff_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='plaintiff_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='assignee_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
