# Generated by Django 4.2.18 on 2025-02-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_plaintiffdetails_case_delete_defendantdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaintiffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintiff', models.TextField(blank=True, null=True)),
                ('plaintiff_law_firm', models.TextField(blank=True, null=True)),
                ('plaintiff_attorney_name', models.TextField(blank=True, null=True)),
                ('plaintiff_contact', models.TextField(blank=True, null=True)),
                ('plaintiff_email', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='DefendantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant', models.TextField(blank=True, null=True)),
                ('defendant_law_firm', models.TextField(blank=True, null=True)),
                ('defendant_attorney_name', models.TextField(blank=True, null=True)),
                ('defendant_phone', models.TextField(blank=True, null=True)),
                ('defendant_email', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case')),
            ],
        ),
    ]
