# Generated by Django 4.2.9 on 2025-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_rawdata_accused_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="acquisition_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="art_unit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="assigned_judge",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_closed_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="case_strength_level",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="court_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="current_assignee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="industry",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="original_assignee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="single_or_multiple",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="tech_category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="tech_center",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="third_party_funding_involved",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="type_of_infringement",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="winning_party",
            field=models.TextField(blank=True, null=True),
        ),
    ]
