# Generated by Django 4.2.18 on 2025-02-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_defendent_type_and_size_casedetails_defendent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case', unique=True),
        ),
    ]
