# Generated by Django 4.2.9 on 2025-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_rawdata_acquisition_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdata",
            name="is_valid",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
