# Generated by Django 4.2.18 on 2025-02-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_plaintiffdetails_defendantdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaintiffdetails',
            name='case',
        ),
        migrations.DeleteModel(
            name='DefendantDetails',
        ),
        migrations.DeleteModel(
            name='PlaintiffDetails',
        ),
    ]
