# Generated by Django 4.2.18 on 2025-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_casedetails_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='assignee_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
