# Generated by Django 4.2.18 on 2025-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_patent_assignee_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='chances_of_winning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='chances_of_winning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='casepatent',
            unique_together={('case', 'patent')},
        ),
    ]
