# Generated by Django 4.2.9 on 2025-01-15 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_rawdata_is_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_no", models.CharField(max_length=100, unique=True)),
                ("complaint_date", models.TextField(blank=True, null=True)),
                ("case_name", models.TextField(blank=True, null=True)),
                (
                    "case_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("court_name", models.TextField(blank=True, null=True)),
                ("litigation_venues", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patent_no", models.CharField(max_length=100, unique=True)),
                ("patent_type", models.TextField(blank=True, null=True)),
                ("patent_title", models.TextField(blank=True, null=True)),
                ("original_assignee", models.TextField(blank=True, null=True)),
                ("current_assignee", models.TextField(blank=True, null=True)),
                ("issue_date", models.TextField(blank=True, null=True)),
                ("expiry_date", models.TextField(blank=True, null=True)),
                ("single_or_multiple", models.TextField(blank=True, null=True)),
                (
                    "standard_patent",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "semiconductor_patent",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tech_center", models.TextField(blank=True, null=True)),
                ("art_unit", models.TextField(blank=True, null=True)),
                ("acquisition_type", models.TextField(blank=True, null=True)),
                ("assignee_timeline", models.TextField(blank=True, null=True)),
                ("industry", models.TextField(blank=True, null=True)),
                ("technology_keywords", models.TextField(blank=True, null=True)),
                ("tech_category", models.TextField(blank=True, null=True)),
                ("reason_of_allowance", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CasePatent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.case"
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.patent"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="patents",
            field=models.ManyToManyField(
                related_name="cases", through="mainapp.CasePatent", to="mainapp.patent"
            ),
        ),
    ]
