# Generated by Django 4.2.9 on 2025-01-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_case_patent_casepatent_case_patents"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("related_cases", models.TextField(blank=True, null=True)),
                ("case_closed_date", models.TextField(blank=True, null=True)),
                ("cause_of_action", models.TextField(blank=True, null=True)),
                ("accused_product", models.TextField(blank=True, null=True)),
                ("judge", models.TextField(blank=True, null=True)),
                (
                    "number_of_infringed_claims",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "third_party_funding_involved",
                    models.TextField(blank=True, null=True),
                ),
                ("type_of_infringement", models.TextField(blank=True, null=True)),
                ("case_strength_level", models.TextField(blank=True, null=True)),
                ("recent_action", models.TextField(blank=True, null=True)),
                ("winning_amount", models.TextField(blank=True, null=True)),
                ("winning_party", models.TextField(blank=True, null=True)),
                ("other_possible_infringer", models.TextField(blank=True, null=True)),
                ("list_of_prior_art", models.TextField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.case"
                    ),
                ),
            ],
        ),
    ]
