# Generated by Django 4.2.9 on 2025-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_casedetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedetails",
            name="activity_timeline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="defendant",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="defendent_type_and_size",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="no_of_defendents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="other_defendents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="plaintiff",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="plaintiff_type_and_size",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casedetails",
            name="stage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
