# Generated by Django 5.2.1 on 2025-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_set_patent_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='acquisition_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='art_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='current_assignee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='expiry_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='industry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='issue_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='original_assignee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='reason_of_allowance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='single_or_multiple',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tech_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tech_center',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='technology_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
