# Generated by Django 5.2.1 on 2025-06-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_set_patent_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case'),
        ),
    ]
