# Generated by Django 5.2.1 on 2025-06-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_customuser_is_staff_alter_casedetails_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case', unique=True),
        ),
    ]
