# Generated by Django 5.2.1 on 2025-06-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_casedetails_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
