# Generated by Django 5.2.1 on 2025-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rawdata_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='defendent_type_and_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='plaintiff_type_and_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
