# Generated by Django 5.2.1 on 2025-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rawdata_defendent_type_and_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='defendent_type_and_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='plaintiff_type_and_size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
