# Generated by Django 5.2.1 on 2025-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_casedetails_defendent_type_and_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='plaintiff_type_and_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
