"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 2.2.4, updated for better practices.
"""
from decouple import config
import os
import dj_database_url
from dotenv import load_dotenv
# from dotenv import load_dotenv
from datetime import timedelta
from pathlib import Path

# Add to your settings.py
MEDIA_URL = '/media/'
# import os
load_dotenv()
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
# MEDIA_ROOT = BASE_DIR / 'media'
# load_dotenv()
# OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
OPENROUTER_MODEL = 'deepseek/deepseek-r1-0528:free'
# OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Security for Production
SECURE_SSL_REDIRECT = os.getenv('DJANGO_ENV', 'development') == 'production'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_ENV', 'development') == 'production'
SESSION_COOKIE_SECURE = os.getenv('DJANGO_ENV', 'development') == 'production'


# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = BASE_DIR / 'media'

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for production
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '=)6fvl-@-)f$%bwd@fsda(yp2p#&$-!_*o@q2_$na6_m$3(n#r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['18.216.104.19', '18.220.232.127', 'localhost', '127.0.0.1','xli-360-backend-1.onrender.com']

# Google OAuth credentials (use environment variables in production)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '511014243371-d0q42ehfg2l40rc722t0n6oep2hl08pd.apps.googleusercontent.com')
GOOGLE_CLIENT_SECRET_ID = os.getenv('GOOGLE_CLIENT_SECRET_ID', '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')

# Custom user model
AUTH_USER_MODEL = 'mainapp.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add OAuth backend if using Google OAuth
    # 'social_core.backends.google.GoogleOAuth2',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'mainapp',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://ec2-18-216-104-19.us-east-2.compute.amazonaws.com",
    "http://ec2-18-220-232-127.us-east-2.compute.amazonaws.com",
    "http://18.220.232.127", 

]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'

# DEBUG = True
# ALLOWED_HOSTS = ['*']  # temporarily allow all for debugging


# Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'LitigationDb'),
#         'USER': os.getenv('DB_USER', 'Sarita'),
#         'PASSWORD': os.getenv('DB_PASSWORD', 'Bayslope_23'),
#         'HOST': os.getenv('DB_HOST', 'restored-db-april29-newlitigation-july-25.cd842y2iqcq8.us-east-2.rds.amazonaws.com'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#         'CONN_MAX_AGE': 0,  # Close connections after each request to prevent exhaustion
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'litigation_db',
#         'USER': 'postgres',
#         'PASSWORD': 'admin',
#         'HOST': 'localhost',
#         'PORT': '5432',
#         'CONN_MAX_AGE': 0,
#     }
# }



DATABASES = {
    'default': dj_database_url.parse(
        "postgresql://xli360_db_user:kZFDzQxViQIWZAIOhBapMwoPMSIFuXHw@dpg-d1v4c3juibrs73923ilg-a/xli360_db",
        conn_max_age=600
    )
}

# REST Framework and JWT settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=50),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_BLACKLIST_ENABLED': True,
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',  # Changed to INFO for production
            'propagate': False,
        },
        'mainapp': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Security settings
SECURE_SSL_REDIRECT = False  # Enable in production with HTTPS
CSRF_COOKIE_SECURE = False  # Enable in production
SESSION_COOKIE_SECURE = False  # Enable in production

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

CORS_ALLOW_ALL_ORIGINS = True  # Safe for dev, restrict in prod
